language: node_js

node_js: 12.10.0

cache:
  directories:
    - node_modules

install:
  - yarn install

before_script:
  - rm .gitignore
  - echo node_modules > .gitignore

script:
  - yarn build
  - yarn api:build
  - yarn docs:build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $EZDIAGRAM 
  local_dir: docs/.vuepress/dist
  on:
    branch: main