language: node_js

node_js: 12.10.0

cache:
  directories:
    - node_modules

install:
  - yarn install

before_script:
  - rm .gitignore

script:
  - yarn build
  - yarn apidocs
  - yarn docs:build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $EZDIAGRAM 
  on:
    branch: main