language: node_js

node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $EZDIAGRAM  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: gh-pages