export const BUILTIN_PLGUIN = {
    BACKGROUND:'BACKGROUND',
    CONNECT_VERTEX:'CONNECT_VERTEX',
    EDGE_GENERATOR:'EDGE_GENERATOR',
    HOT_KEY:'HOT_KEY',
    SELECT:'SELECT',
    SINGLE_LINE_HANDLER:'SINGLE_LINE_HANDLER',
    SINGLE_VERTEX_HANDLER:'SINGLE_VERTEX_HANDLER', 
    VERTEX_TEXT_EDITOR:'VERTEX_TEXT_EDITOR',
};